/**
* @author Vinay CN
* @date 
* @description : Landing Page Wrapper.
Modification Log:
------------------------------------------------------------------------------------
Developer Mod Number Date Description
------------------------------------------------------------------------------------
*/
public class Sdo_scom_recordlist_lightning_response{ 
    public Sdo_scom_recordlist_datatable_response lstDataTableRecs; 
    public sdo_scom_recordlist_lightning_response(){
    }   
}